### ISSUE TITLE
Add DocFx metadata element

### ISSUE THREAD

**Issue by Cloud-Awesome** [Cloud-Awesome/markdown-maker#1]
e.g. something to replace this:

```
var docfxMetadata = 
    "---" + Environment.NewLine +
    "uid: this_is_a_tester" + Environment.NewLine +
    "---";
```

`new MdDocFxMetadata(key, value)`

**Comment by Cloud-Awesome** [comment]
This maybe needs a yaml generator class too... 

e.g.

```
---
documentType: tester
seeAlso:
  - uid: this_is_a_uid
    name: New page
  - uid: this_is_another_uid
    name: Second page
---
```

Consider whether this is a new class within the md maker, or a separate project for yml..?
